[platformio]
default_envs = ghostble_cardputer

[env:ghostble_cardputer]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = m5stack-cardputer
board_build.partitions = partitions.csv
framework = arduino
build_flags = 
    -DCARDPUTER
    -DCONFIG_BT_NIMBLE_EXT_ADV=1
    -I src

monitor_speed = 115200
#monitor_filters = esp32_exception_decoder
lib_deps =
    m5stack/M5Cardputer
    m5stack/M5Unified
    h2zero/NimBLE-Arduino
    mathieucarbou/AsyncTCP@^3.2.14
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    mikalhart/TinyGPSPlus

[env:ghostble_sticks3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = m5stack-stamps3
board_build.partitions = partitions.csv
framework = arduino
build_flags =
    -DM5STICKS3
    -I src
    -DCONFIG_BT_NIMBLE_EXT_ADV=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
#monitor_filters = esp32_exception_decoder
lib_deps =
    m5stack/M5Unified
    h2zero/NimBLE-Arduino
    mathieucarbou/AsyncTCP@^3.2.14
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    mikalhart/TinyGPSPlus    

[env:native]
platform = native
test_framework = googletest
build_flags =
    -std=gnu++17
    -I src
    -I test/mocks